<?php

use Illuminate\Database\Seeder;

class CountriesProvincesCitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['id' => 1, 'name' => 'República de Venezuela'],
            /*['id' => 2, 'name' => 'Argentina'],
            ['id' => 3, 'name' => 'Estado Plurinacional de Bolivia'],
            ['id' => 4, 'name' => 'República Federativa del Brasil'],
            ['id' => 5, 'name' => 'República de Chile'],
            ['id' => 6, 'name' => 'República de Colombia'],
            ['id' => 7, 'name' => 'Costa Rica'],
            ['id' => 8, 'name' => 'República Dominicana'],
            ['id' => 9, 'name' => 'República del Ecuador'],
            ['id' => 10, 'name' => 'República de El Salvador'],
            ['id' => 11, 'name' => 'Ecuador'],
            ['id' => 12, 'name' => 'Reino de España'],
            ['id' => 13, 'name' => 'Estados Unidos de América'],*/
        ];

        $provinces = [
            /* Venezuela */
            ['id' => 1, 'country_id' => 1, 'name' => 'Amazonas'],
            ['id' => 2, 'country_id' => 1, 'name' => 'Anzoátegui'],
            ['id' => 3, 'country_id' => 1, 'name' => 'Apure'],
            ['id' => 4, 'country_id' => 1, 'name' => 'Aragua'],
            ['id' => 5, 'country_id' => 1, 'name' => 'Barinas'],
            ['id' => 6, 'country_id' => 1, 'name' => 'Bolívar'],
            ['id' => 7, 'country_id' => 1, 'name' => 'Carabobo'],
            ['id' => 8, 'country_id' => 1, 'name' => 'Cojedes'],
            ['id' => 9, 'country_id' => 1, 'name' => 'Delta Amacuro'],
            ['id' => 10, 'country_id' => 1, 'name' => 'Distrito Capital'],
            ['id' => 11, 'country_id' => 1, 'name' => 'Falcón'],
            ['id' => 12, 'country_id' => 1, 'name' => 'Guárico'],
            ['id' => 13, 'country_id' => 1, 'name' => 'Lara'],
            ['id' => 14, 'country_id' => 1, 'name' => 'Mérida'],
            ['id' => 15, 'country_id' => 1, 'name' => 'Miranda'],
            ['id' => 16, 'country_id' => 1, 'name' => 'Monagas'],
            ['id' => 17, 'country_id' => 1, 'name' => 'Nueva Esparta'],
            ['id' => 18, 'country_id' => 1, 'name' => 'Portuguesa'],
            ['id' => 19, 'country_id' => 1, 'name' => 'Sucre'],
            ['id' => 20, 'country_id' => 1, 'name' => 'Táchira'],
            ['id' => 21, 'country_id' => 1, 'name' => 'Trujillo'],
            ['id' => 22, 'country_id' => 1, 'name' => 'Vargas'],
            ['id' => 23, 'country_id' => 1, 'name' => 'Yaracuy'],
            ['id' => 24, 'country_id' => 1, 'name' => 'Zulia'],
            ['id' => 25, 'country_id' => 1, 'name' => 'Dependencias Federales'],
        ];

        $cities = [
            /* Amazonas */
            ['id' => 1, 'province_id' => 1, 'name' => 'La Esmeralda'],
            ['id' => 2, 'province_id' => 1, 'name' => 'San Fernando de Atabapo'],
            ['id' => 3, 'province_id' => 1, 'name' => 'Puerto Ayacucho'],
            ['id' => 4, 'province_id' => 1, 'name' => 'Puerto Ayacucho'],
            ['id' => 5, 'province_id' => 1, 'name' => 'Isla Ratón'],
            ['id' => 6, 'province_id' => 1, 'name' => 'Maroa'],
            ['id' => 7, 'province_id' => 1, 'name' => 'San Juan de Manapiare'],
            ['id' => 8, 'province_id' => 1, 'name' => 'San Carlos de Río Negro'],
            /* Anzoategui */
            ['id' => 9, 'province_id' => 2, 'name' => 'Anaco'],
            ['id' => 10, 'province_id' => 2, 'name' => 'Aragua de Barcelona'],
            ['id' => 11, 'province_id' => 2, 'name' => 'Puerto Píritu'],
            ['id' => 12, 'province_id' => 2, 'name' => 'Valle de Guanape'],
            ['id' => 13, 'province_id' => 2, 'name' => 'Pariaguán'],
            ['id' => 14, 'province_id' => 2, 'name' => 'Guanta'],
            ['id' => 15, 'province_id' => 2, 'name' => 'Soledad'],
            ['id' => 16, 'province_id' => 2, 'name' => 'Puerto La Cruz'],
            ['id' => 17, 'province_id' => 2, 'name' => 'Onoto'],
            ['id' => 18, 'province_id' => 2, 'name' => 'Mapire'],
            ['id' => 19, 'province_id' => 2, 'name' => 'San Mateo'],
            ['id' => 20, 'province_id' => 2, 'name' => 'Clarines'],
            ['id' => 21, 'province_id' => 2, 'name' => 'Cantaura'],
            ['id' => 22, 'province_id' => 2, 'name' => 'Píritu'],
            ['id' => 23, 'province_id' => 2, 'name' => 'San José de Guanipa (El Tigrito)'],
            ['id' => 24, 'province_id' => 2, 'name' => 'Boca de Uchire'],
            ['id' => 25, 'province_id' => 2, 'name' => 'Santa Ana'],
            ['id' => 26, 'province_id' => 2, 'name' => 'Barcelona'],
            ['id' => 27, 'province_id' => 2, 'name' => 'El Tigre'],
            ['id' => 28, 'province_id' => 2, 'name' => 'El Chaparro'],
            ['id' => 29, 'province_id' => 2, 'name' => 'Lecherías'],
            /* Apure */
            ['id' => 30, 'province_id' => 3, 'name' => 'Achaguas'],
            ['id' => 31, 'province_id' => 3, 'name' => 'Biruaca'],
            ['id' => 32, 'province_id' => 3, 'name' => 'Bruzual'],
            ['id' => 33, 'province_id' => 3, 'name' => 'Guasdualito'],
            ['id' => 34, 'province_id' => 3, 'name' => 'San Juan de Payara'],
            ['id' => 35, 'province_id' => 3, 'name' => 'Elorza'],
            ['id' => 36, 'province_id' => 3, 'name' => 'San Fernando de Apure'],
            /* Aragua */
            ['id' => 37, 'province_id' => 4, 'name' => 'San Mateo'],
            ['id' => 38, 'province_id' => 4, 'name' => 'Camatagua'],
            ['id' => 39, 'province_id' => 4, 'name' => 'Maracay'],
            ['id' => 40, 'province_id' => 4, 'name' => 'Santa Cruz'],
            ['id' => 41, 'province_id' => 4, 'name' => 'La Victoria'],
            ['id' => 42, 'province_id' => 4, 'name' => 'El Consejo'],
            ['id' => 43, 'province_id' => 4, 'name' => 'Palo Negro'],
            ['id' => 44, 'province_id' => 4, 'name' => 'El Limón'],
            ['id' => 45, 'province_id' => 4, 'name' => 'San Casimiro'],
            ['id' => 46, 'province_id' => 4, 'name' => 'San Sebastián de Los Reyes'],
            ['id' => 47, 'province_id' => 4, 'name' => 'Turmero'],
            ['id' => 48, 'province_id' => 4, 'name' => 'Las Tejerías'],
            ['id' => 49, 'province_id' => 4, 'name' => 'Cagua'],
            ['id' => 50, 'province_id' => 4, 'name' => 'La Colonia Tovar'],
            ['id' => 51, 'province_id' => 4, 'name' => 'Barbacoas'],
            ['id' => 52, 'province_id' => 4, 'name' => 'Villa de Cura'],
            ['id' => 53, 'province_id' => 4, 'name' => 'Santa Rita'],
            ['id' => 54, 'province_id' => 4, 'name' => 'Santa'],
            ['id' => 55, 'province_id' => 4, 'name' => 'Ocumare de la Costa'],
            /* Barinas */
            ['id' => 56, 'province_id' => 5, 'name' => 'Sabaneta'],
            ['id' => 57, 'province_id' => 5, 'name' => 'Socopó'],
            ['id' => 58, 'province_id' => 5, 'name' => 'Arismendi'],
            ['id' => 59, 'province_id' => 5, 'name' => 'Barinas'],
            ['id' => 60, 'province_id' => 5, 'name' => 'Barinitas'],
            ['id' => 61, 'province_id' => 5, 'name' => 'Barrancas'],
            ['id' => 62, 'province_id' => 5, 'name' => 'Santa Bárbara'],
            ['id' => 63, 'province_id' => 5, 'name' => 'Obispos'],
            ['id' => 64, 'province_id' => 5, 'name' => 'Ciudad Bolivia'],
            ['id' => 65, 'province_id' => 5, 'name' => 'Libertad'],
            ['id' => 66, 'province_id' => 5, 'name' => 'Ciudad de Nutrias'],
            ['id' => 67, 'province_id' => 5, 'name' => 'El Cantón'],
            /* Bolívar */
            ['id' => 68, 'province_id' => 6, 'name' => 'Ciudad Guayana'],
            ['id' => 69, 'province_id' => 6, 'name' => 'Caicara del Orinoco'],
            ['id' => 70, 'province_id' => 6, 'name' => 'El Callao'],
            ['id' => 71, 'province_id' => 6, 'name' => 'Santa Elena de Uairén'],
            ['id' => 72, 'province_id' => 6, 'name' => 'Ciudad Bolívar'],
            ['id' => 73, 'province_id' => 6, 'name' => 'Upata'],
            ['id' => 74, 'province_id' => 6, 'name' => 'Ciudad Piar'],
            ['id' => 75, 'province_id' => 6, 'name' => 'Ciudad Piar'],
            ['id' => 76, 'province_id' => 6, 'name' => 'Guasipati'],
            ['id' => 77, 'province_id' => 6, 'name' => 'Tumeremo'],
            ['id' => 78, 'province_id' => 6, 'name' => 'Maripa'],
            ['id' => 79, 'province_id' => 6, 'name' => 'El Palmar'],
            /* Carabobo */
            ['id' => 80, 'province_id' => 7, 'name' => 'Bejuma'],
            ['id' => 81, 'province_id' => 7, 'name' => 'Güigüe'],
            ['id' => 82, 'province_id' => 7, 'name' => 'Mariara'],
            ['id' => 83, 'province_id' => 7, 'name' => 'Guacara'],
            ['id' => 84, 'province_id' => 7, 'name' => 'Morón'],
            ['id' => 85, 'province_id' => 7, 'name' => 'Tocuyito'],
            ['id' => 86, 'province_id' => 7, 'name' => 'Los Guayos'],
            ['id' => 87, 'province_id' => 7, 'name' => 'Miranda'],
            ['id' => 88, 'province_id' => 7, 'name' => 'Montalbán'],
            ['id' => 89, 'province_id' => 7, 'name' => 'Naguanagua'],
            ['id' => 90, 'province_id' => 7, 'name' => 'Puerto Cabello'],
            ['id' => 91, 'province_id' => 7, 'name' => 'San Diego'],
            ['id' => 92, 'province_id' => 7, 'name' => 'San Joaquín'],
            ['id' => 93, 'province_id' => 7, 'name' => 'Valencia'],
            /* Cojedes */
            ['id' => 94, 'province_id' => 8, 'name' => 'Cojedes'],
            ['id' => 95, 'province_id' => 8, 'name' => 'Tinaquillo'],
            ['id' => 96, 'province_id' => 8, 'name' => 'El Baúl'],
            ['id' => 97, 'province_id' => 8, 'name' => 'Macapo'],
            ['id' => 98, 'province_id' => 8, 'name' => 'El Pao'],
            ['id' => 99, 'province_id' => 8, 'name' => 'Libertad'],
            ['id' => 100, 'province_id' => 8, 'name' => 'Las Vegas'],
            ['id' => 101, 'province_id' => 8, 'name' => 'San Carlos'],
            ['id' => 102, 'province_id' => 8, 'name' => 'Tinaco'],
            /* Delta Amacuro */
            ['id' => 103, 'province_id' => 9, 'name' => 'Curiapo'],
            ['id' => 104, 'province_id' => 9, 'name' => 'Sierra Imataca'],
            ['id' => 105, 'province_id' => 9, 'name' => 'Pedernales'],
            ['id' => 106, 'province_id' => 9, 'name' => 'Tucupita'],
            /* Distrito Capital */
            ['id' => 107, 'province_id' => 10, 'name' => 'Caracas'],
            /* Falcón */
            ['id' => 108, 'province_id' => 11, 'name' => 'San Juan de los Cayos'],
            ['id' => 109, 'province_id' => 11, 'name' => 'San Luis'],
            ['id' => 110, 'province_id' => 11, 'name' => 'Capatárida'],
            ['id' => 111, 'province_id' => 11, 'name' => 'Yaracal'],
            ['id' => 112, 'province_id' => 11, 'name' => 'Punto Fijo'],
            ['id' => 113, 'province_id' => 11, 'name' => 'La Vela de Coro'],
            ['id' => 114, 'province_id' => 11, 'name' => 'Dabajuro'],
            ['id' => 115, 'province_id' => 11, 'name' => 'Pedregal'],
            ['id' => 116, 'province_id' => 11, 'name' => 'Pueblo Nuevo'],
            ['id' => 117, 'province_id' => 11, 'name' => 'Churuguara'],
            ['id' => 118, 'province_id' => 11, 'name' => 'Jacura'],
            ['id' => 119, 'province_id' => 11, 'name' => 'Santa Cruz de Los Taques'],
            ['id' => 120, 'province_id' => 11, 'name' => 'Mene de Mauroa'],
            ['id' => 121, 'province_id' => 11, 'name' => 'Santa Ana de Coro'],
            ['id' => 122, 'province_id' => 11, 'name' => 'Chichiriviche'],
            ['id' => 123, 'province_id' => 11, 'name' => 'Palmasola'],
            ['id' => 124, 'province_id' => 11, 'name' => 'Cabure'],
            ['id' => 125, 'province_id' => 11, 'name' => 'Píritu'],
            ['id' => 126, 'province_id' => 11, 'name' => 'Mirimire'],
            ['id' => 127, 'province_id' => 11, 'name' => 'La Cruz de Taratara'],
            ['id' => 128, 'province_id' => 11, 'name' => 'Tocópero'],
            ['id' => 129, 'province_id' => 11, 'name' => 'Santa Cruz de Bucaral'],
            ['id' => 130, 'province_id' => 11, 'name' => 'Urumaco'],
            ['id' => 131, 'province_id' => 11, 'name' => 'Puerto Cumarebo'],
            /* Guárico */
            ['id' => 132, 'province_id' => 12, 'name' => 'Camaguán'],
            ['id' => 133, 'province_id' => 12, 'name' => 'Chaguaramas'],
            ['id' => 134, 'province_id' => 12, 'name' => 'El Socorro'],
            ['id' => 135, 'province_id' => 12, 'name' => 'Guayabal'],
            ['id' => 136, 'province_id' => 12, 'name' => 'Valle de La Pascua'],
            ['id' => 137, 'province_id' => 12, 'name' => 'Las Mercedes'],
            ['id' => 138, 'province_id' => 12, 'name' => 'El Sombrero'],
            ['id' => 139, 'province_id' => 12, 'name' => 'Calabozo'],
            ['id' => 140, 'province_id' => 12, 'name' => 'Altagracia de Orituco'],
            ['id' => 141, 'province_id' => 12, 'name' => 'Ortiz'],
            ['id' => 142, 'province_id' => 12, 'name' => 'Tucupido'],
            ['id' => 143, 'province_id' => 12, 'name' => 'San Juan de los Morros'],
            ['id' => 144, 'province_id' => 12, 'name' => 'San José de Guaribe'],
            ['id' => 145, 'province_id' => 12, 'name' => 'Santa María de Ipire'],
            ['id' => 146, 'province_id' => 12, 'name' => 'Zaraza'],
            /* Lara */
            ['id' => 147, 'province_id' => 13, 'name' => 'Sanare'],
            ['id' => 148, 'province_id' => 13, 'name' => 'Duaca'],
            ['id' => 149, 'province_id' => 13, 'name' => 'Barquisimeto'],
            ['id' => 150, 'province_id' => 13, 'name' => 'Quíbor'],
            ['id' => 151, 'province_id' => 13, 'name' => 'El Tocuyo'],
            ['id' => 152, 'province_id' => 13, 'name' => 'Cabudare'],
            ['id' => 153, 'province_id' => 13, 'name' => 'Sarare'],
            ['id' => 154, 'province_id' => 13, 'name' => 'Carora'],
            ['id' => 155, 'province_id' => 13, 'name' => 'Siquisique'],
            /* Mérida */
            ['id' => 156, 'province_id' => 14, 'name' => 'El Vigía'],
            ['id' => 157, 'province_id' => 14, 'name' => 'La Azulita'],
            ['id' => 158, 'province_id' => 14, 'name' => 'Santa Cruz de Mora'],
            ['id' => 159, 'province_id' => 14, 'name' => 'Aricagua'],
            ['id' => 160, 'province_id' => 14, 'name' => 'Canaguá'],
            ['id' => 161, 'province_id' => 14, 'name' => 'Ejido'],
            ['id' => 162, 'province_id' => 14, 'name' => 'Tucaní'],
            ['id' => 163, 'province_id' => 14, 'name' => 'Santo Domingo'],
            ['id' => 164, 'province_id' => 14, 'name' => 'Guaraque'],
            ['id' => 165, 'province_id' => 14, 'name' => 'Arapuey'],
            ['id' => 166, 'province_id' => 14, 'name' => 'Torondoy'],
            ['id' => 167, 'province_id' => 14, 'name' => 'Mérida'],
            ['id' => 168, 'province_id' => 14, 'name' => 'Timotes'],
            ['id' => 169, 'province_id' => 14, 'name' => 'Santa Elena de Arenales'],
            ['id' => 170, 'province_id' => 14, 'name' => 'Santa María de Caparo'],
            ['id' => 171, 'province_id' => 14, 'name' => 'Pueblo Llano'],
            ['id' => 172, 'province_id' => 14, 'name' => 'Mucuchíes'],
            ['id' => 173, 'province_id' => 14, 'name' => 'Bailadores'],
            ['id' => 174, 'province_id' => 14, 'name' => 'Tabay'],
            ['id' => 175, 'province_id' => 14, 'name' => 'Lagunillas'],
            ['id' => 176, 'province_id' => 14, 'name' => 'Tovar'],
            ['id' => 177, 'province_id' => 14, 'name' => 'Nueva Bolivia'],
            ['id' => 178, 'province_id' => 14, 'name' => 'Zea'],
            /* Miranda */ ########################################
            ['id' => 178, 'province_id' => 15, 'name' => 'Caucagua'],
            ['id' => 179, 'province_id' => 15, 'name' => 'San José de Barlovento'],
            ['id' => 180, 'province_id' => 15, 'name' => 'Nuestra Señora del Rosario de Baruta'],
            ['id' => 181, 'province_id' => 15, 'name' => 'Higuerote'],
            ['id' => 182, 'province_id' => 15, 'name' => 'Mamporal'],
            ['id' => 183, 'province_id' => 15, 'name' => 'Carrizal'],
            ['id' => 184, 'province_id' => 15, 'name' => 'Chacao'],
            ['id' => 185, 'province_id' => 15, 'name' => 'Charallave'],
            ['id' => 186, 'province_id' => 15, 'name' => 'El Hatillo'],
            ['id' => 187, 'province_id' => 15, 'name' => 'Los Teques'],
            ['id' => 188, 'province_id' => 15, 'name' => 'Santa Teresa del Tuy'],
            ['id' => 189, 'province_id' => 15, 'name' => 'Ocumare del Tuy'],
            ['id' => 190, 'province_id' => 15, 'name' => 'San Antonio de Los Altos'],
            ['id' => 191, 'province_id' => 15, 'name' => 'Río Chico'],
            ['id' => 192, 'province_id' => 15, 'name' => 'Santa Lucía'],
            ['id' => 193, 'province_id' => 15, 'name' => 'Cúpira'],
            ['id' => 194, 'province_id' => 15, 'name' => 'Guarenas'],
            ['id' => 195, 'province_id' => 15, 'name' => 'San Francisco de Yare'],
            ['id' => 196, 'province_id' => 15, 'name' => 'Petare'],
            ['id' => 197, 'province_id' => 15, 'name' => 'Cúa'],
            ['id' => 198, 'province_id' => 15, 'name' => 'Guatire'],
            /* Monagas */
            ['id' => 199, 'province_id' => 16, 'name' => 'San Antonio'],
            ['id' => 200, 'province_id' => 16, 'name' => 'Aguasay'],
            ['id' => 201, 'province_id' => 16, 'name' => 'Caripito'],
            ['id' => 202, 'province_id' => 16, 'name' => 'Caripe'],
            ['id' => 203, 'province_id' => 16, 'name' => 'Caicara'],
            ['id' => 204, 'province_id' => 16, 'name' => 'Punta de Mata'],
            ['id' => 205, 'province_id' => 16, 'name' => 'Temblador'],
            ['id' => 206, 'province_id' => 16, 'name' => 'Maturín'],
            ['id' => 207, 'province_id' => 16, 'name' => 'Aragua'],
            ['id' => 208, 'province_id' => 16, 'name' => 'Quiriquire'],
            ['id' => 209, 'province_id' => 16, 'name' => 'Santa Bárbara'],
            ['id' => 210, 'province_id' => 16, 'name' => 'Barrancas'],
            ['id' => 211, 'province_id' => 16, 'name' => 'Uracoa'],
            /* Nueva Esparta */
            ['id' => 212, 'province_id' => 17, 'name' => 'La Plaza de Paraguachí'],
            ['id' => 213, 'province_id' => 17, 'name' => 'La Asunción'],
            ['id' => 214, 'province_id' => 17, 'name' => 'San Juan Bautista'],
            ['id' => 215, 'province_id' => 17, 'name' => 'El Valle del Espíritu Santo'],
            ['id' => 216, 'province_id' => 17, 'name' => 'Santa Ana'],
            ['id' => 217, 'province_id' => 17, 'name' => 'Pampatar'],
            ['id' => 218, 'province_id' => 17, 'name' => 'Juangriego'],
            ['id' => 219, 'province_id' => 17, 'name' => 'Porlamar'],
            ['id' => 220, 'province_id' => 17, 'name' => 'Boca del Río'],
            ['id' => 221, 'province_id' => 17, 'name' => 'Punta de Piedras'],
            ['id' => 222, 'province_id' => 17, 'name' => 'San Pedro de Coche'],
            /* Portuguesa */
            ['id' => 223, 'province_id' => 18, 'name' => 'Agua Blanca'],
            ['id' => 224, 'province_id' => 18, 'name' => 'Araure'],
            ['id' => 225, 'province_id' => 18, 'name' => 'Píritu'],
            ['id' => 226, 'province_id' => 18, 'name' => 'Guanare'],
            ['id' => 227, 'province_id' => 18, 'name' => 'Guanarito'],
            ['id' => 228, 'province_id' => 18, 'name' => 'Paraíso de Chabasquén'],
            ['id' => 229, 'province_id' => 18, 'name' => 'Ospino'],
            ['id' => 230, 'province_id' => 18, 'name' => 'Acarigua'],
            ['id' => 231, 'province_id' => 18, 'name' => 'Papelón'],
            ['id' => 232, 'province_id' => 18, 'name' => 'Boconoito'],
            ['id' => 233, 'province_id' => 18, 'name' => 'San Rafael de Onoto'],
            ['id' => 234, 'province_id' => 18, 'name' => 'El Playón'],
            ['id' => 235, 'province_id' => 18, 'name' => 'Biscucuy'],
            ['id' => 236, 'province_id' => 18, 'name' => 'Villa Bruzual'],
            /* Sucre */
            ['id' => 237, 'province_id' => 19, 'name' => 'Casanay'],
            ['id' => 238, 'province_id' => 19, 'name' => 'San José de Aerocuar'],
            ['id' => 239, 'province_id' => 19, 'name' => 'Río Caribe'],
            ['id' => 240, 'province_id' => 19, 'name' => 'El Pilar'],
            ['id' => 241, 'province_id' => 19, 'name' => 'Carúpano'],
            ['id' => 242, 'province_id' => 19, 'name' => 'Marigüitar'],
            ['id' => 243, 'province_id' => 19, 'name' => 'Yaguaraparo'],
            ['id' => 244, 'province_id' => 19, 'name' => 'Araya'],
            ['id' => 245, 'province_id' => 19, 'name' => 'Tunapuy'],
            ['id' => 246, 'province_id' => 19, 'name' => 'Irapa'],
            ['id' => 247, 'province_id' => 19, 'name' => 'San Antonio del Golfo'],
            ['id' => 248, 'province_id' => 19, 'name' => 'Cumanacoa'],
            ['id' => 249, 'province_id' => 19, 'name' => 'Cariaco'],
            ['id' => 250, 'province_id' => 19, 'name' => 'Cumaná'],
            ['id' => 251, 'province_id' => 19, 'name' => 'Güiria'],
            /* Táchira */
            ['id' => 252, 'province_id' => 20, 'name' => 'Cordero'],
            ['id' => 253, 'province_id' => 20, 'name' => 'Las Mesas'],
            ['id' => 254, 'province_id' => 20, 'name' => 'Colón'],
            ['id' => 255, 'province_id' => 20, 'name' => 'San Antonio del Táchira'],
            ['id' => 256, 'province_id' => 20, 'name' => 'Táriba'],
            ['id' => 257, 'province_id' => 20, 'name' => 'Santa Ana'],
            ['id' => 258, 'province_id' => 20, 'name' => 'San Rafael del Piñal'],
            ['id' => 259, 'province_id' => 20, 'name' => 'San José de Bolívar'],
            ['id' => 260, 'province_id' => 20, 'name' => 'La Fría'],
            ['id' => 261, 'province_id' => 20, 'name' => 'Palmira'],
            ['id' => 262, 'province_id' => 20, 'name' => 'Capacho Nuevo'],
            ['id' => 263, 'province_id' => 20, 'name' => 'La Grita'],
            ['id' => 264, 'province_id' => 20, 'name' => 'El Cobre'],
            ['id' => 265, 'province_id' => 20, 'name' => 'Rubio'],
            ['id' => 266, 'province_id' => 20, 'name' => 'Capacho Viejo'],
            ['id' => 267, 'province_id' => 20, 'name' => 'Abejales'],
            ['id' => 268, 'province_id' => 20, 'name' => 'Lobatera'],
            ['id' => 269, 'province_id' => 20, 'name' => 'Michelena'],
            ['id' => 270, 'province_id' => 20, 'name' => 'Coloncito'],
            ['id' => 271, 'province_id' => 20, 'name' => 'Ureña'],
            ['id' => 272, 'province_id' => 20, 'name' => 'Delicias'],
            ['id' => 273, 'province_id' => 20, 'name' => 'La Tendida'],
            ['id' => 274, 'province_id' => 20, 'name' => 'San Cristóbal'],
            ['id' => 275, 'province_id' => 20, 'name' => 'Seboruco'],
            ['id' => 276, 'province_id' => 20, 'name' => 'San Simón'],
            ['id' => 277, 'province_id' => 20, 'name' => 'Queniquea'],
            ['id' => 278, 'province_id' => 20, 'name' => 'San Josecito'],
            ['id' => 279, 'province_id' => 20, 'name' => 'Pregonero'],
            ['id' => 280, 'province_id' => 20, 'name' => 'Umuquena'],
            /* Trujillo */
            ['id' => 281, 'province_id' => 21, 'name' => 'Santa Isabel'],
            ['id' => 282, 'province_id' => 21, 'name' => 'Boconó'],
            ['id' => 283, 'province_id' => 21, 'name' => 'Sabana Grande'],
            ['id' => 284, 'province_id' => 21, 'name' => 'Chejendé'],
            ['id' => 285, 'province_id' => 21, 'name' => 'Carache'],
            ['id' => 286, 'province_id' => 21, 'name' => 'Escuque'],
            ['id' => 287, 'province_id' => 21, 'name' => 'El Paradero'],
            ['id' => 288, 'province_id' => 21, 'name' => 'Campo Elías'],
            ['id' => 289, 'province_id' => 21, 'name' => 'Santa Apolonia'],
            ['id' => 290, 'province_id' => 21, 'name' => 'El Dividive'],
            ['id' => 291, 'province_id' => 21, 'name' => 'Monte Carmelo'],
            ['id' => 292, 'province_id' => 21, 'name' => 'Motatán'],
            ['id' => 293, 'province_id' => 21, 'name' => 'Pampán'],
            ['id' => 294, 'province_id' => 21, 'name' => 'Pampanito'],
            ['id' => 295, 'province_id' => 21, 'name' => 'Betijoque'],
            ['id' => 296, 'province_id' => 21, 'name' => 'Carvajal'],
            ['id' => 297, 'province_id' => 21, 'name' => 'Sabana de Mendoza'],
            ['id' => 298, 'province_id' => 21, 'name' => 'Trujillo'],
            ['id' => 299, 'province_id' => 21, 'name' => 'La Quebrada'],
            ['id' => 300, 'province_id' => 21, 'name' => 'Valera'],
            /* Vargas */
            ['id' => 301, 'province_id' => 22, 'name' => 'La Guaira'],
            /* Yaracuy */
            ['id' => 302, 'province_id' => 23, 'name' => 'San Pablo'],
            ['id' => 303, 'province_id' => 23, 'name' => 'Aroa'],
            ['id' => 304, 'province_id' => 23, 'name' => 'Chivacoa'],
            ['id' => 305, 'province_id' => 23, 'name' => 'Cocorote'],
            ['id' => 306, 'province_id' => 23, 'name' => 'Independencia'],
            ['id' => 307, 'province_id' => 23, 'name' => 'Sabana de Parra'],
            ['id' => 308, 'province_id' => 23, 'name' => 'Boraure'],
            ['id' => 309, 'province_id' => 23, 'name' => 'Yumare'],
            ['id' => 310, 'province_id' => 23, 'name' => 'Nirgua'],
            ['id' => 311, 'province_id' => 23, 'name' => 'Yaritagua'],
            ['id' => 312, 'province_id' => 23, 'name' => 'San Felipe'],
            ['id' => 313, 'province_id' => 23, 'name' => 'Guama'],
            ['id' => 314, 'province_id' => 23, 'name' => 'Urachiche'],
            ['id' => 315, 'province_id' => 23, 'name' => 'Farriar'],
            /* Zulia */
            ['id' => 316, 'province_id' => 24, 'name' => 'El Toro'],
            ['id' => 317, 'province_id' => 24, 'name' => 'San Timoteo'],
            ['id' => 318, 'province_id' => 24, 'name' => 'Cabimas'],
            ['id' => 319, 'province_id' => 24, 'name' => 'Encontrados'],
            ['id' => 320, 'province_id' => 24, 'name' => 'San Carlos del Zulia'],
            ['id' => 321, 'province_id' => 24, 'name' => 'Pueblo Nuevo El Chivo'],
            ['id' => 322, 'province_id' => 24, 'name' => 'La Concepción'],
            ['id' => 323, 'province_id' => 24, 'name' => 'Casigua El Cubo'],
            ['id' => 324, 'province_id' => 24, 'name' => 'Concepción'],
            ['id' => 325, 'province_id' => 24, 'name' => 'Ciudad Ojeda'],
            ['id' => 326, 'province_id' => 24, 'name' => 'Machiques'],
            ['id' => 327, 'province_id' => 24, 'name' => 'San Rafael de El Moján'],
            ['id' => 328, 'province_id' => 24, 'name' => 'Maracaibo'],
            ['id' => 329, 'province_id' => 24, 'name' => 'Los Puertos de Altagracia'],
            ['id' => 330, 'province_id' => 24, 'name' => 'Sinamaica'],
            ['id' => 331, 'province_id' => 24, 'name' => 'La Villa del Rosario'],
            ['id' => 332, 'province_id' => 24, 'name' => 'San Francisco'],
            ['id' => 333, 'province_id' => 24, 'name' => 'Santa Rita'],
            ['id' => 334, 'province_id' => 24, 'name' => 'Tía Juana'],
            ['id' => 335, 'province_id' => 24, 'name' => 'Bobures'],
            ['id' => 336, 'province_id' => 24, 'name' => 'Bachaquero'],
            /* Dependencias Federales */
            ['id' => 337, 'province_id' => 25, 'name' => 'Las Aves'],
            ['id' => 338, 'province_id' => 25, 'name' => 'La Tortuga'],
            ['id' => 339, 'province_id' => 25, 'name' => 'Los Monjes'],
            ['id' => 340, 'province_id' => 25, 'name' => 'Los Roques'],
            ['id' => 341, 'province_id' => 25, 'name' => 'Chimanas'],
            ['id' => 342, 'province_id' => 25, 'name' => 'La Borracha'],
            ['id' => 343, 'province_id' => 25, 'name' => 'Los Testigos'],
            ['id' => 344, 'province_id' => 25, 'name' => 'La Sola'],
            ['id' => 345, 'province_id' => 25, 'name' => 'Roca del Norte'],
            ['id' => 346, 'province_id' => 25, 'name' => 'La Blanquilla'],
            ['id' => 347, 'province_id' => 25, 'name' => 'La Orchila'],
            ['id' => 348, 'province_id' => 25, 'name' => 'De Aves'],
        ];

        foreach ($countries as $key => $country) {
            $country = factory(App\Country::class)
                ->create([
                    'id' => $country['id'],
                    'name' => $country['name'],
                ]);
        }

        foreach ($provinces as $key => $province) {
            factory(App\Province::class)
                ->create([
                    'id' => $province['id'],
                    'country_id' => $province['country_id'],
                    'name' => $province['name'],
                ]);
        }

        foreach ($cities as $key => $city) {
            factory(App\City::class)
                ->create([
                    // 'id' => $city['id'],
                    'province_id' => $city['province_id'],
                    'name' => $city['name'],
                ]);
        }
    }
}
